#java image

FROM openjdk:14-alpine


ARG INSTALL_ZSH="true"
ARG DEBIAN_FRONTEND=noninteractive


#actualizamos
RUN apk update && apk upgrade \
    #añadimos los paquetes
    && apk add git

# Instalamos zsh
RUN apk update && apk upgrade \
    && apk add zsh

# Instalamos oh-my-zsh y reemplazamos la shell
RUN sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" \
    && sed -i 's/ash/zsh/' /etc/passwd \
    && git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k \
    && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# seteamos la configuracion de zsh
COPY .p10k.zsh /root/.p10k.zsh
COPY .zshrc /root/.zshrc
